config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :emailer_forms, only: [:new, :create], path_names: { new: "" }
  get '/' => 'emailer_forms#new', as: 'sent'
  post '/' => 'emailer_forms#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emailer_form.rb
class EmailerForm < ApplicationRecord

  validates :name,
            :proj_url,
            presence: { message: "Please complete all fields" }

  validates :proj_repo,
            presence: { message: "Please complete all fields!" },
            uniqueness: { message: "This repositiry belongs to someone else" }

  validates :email,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      message: "Email format invalid" },
            presence: { message: "Please complete all fields" },
            uniqueness: { message: "Email address has already been used" }

  validates :oop,
            :modular,
            :full_stack,
            :testing,
            :db,
            :debugging,
            :problem_solving,
            :js,
            :html,
            :css,
            :teamwork,
            :self_motivation,
            :communication,
            :energy_level,
            :aptitude,
            numericality: { only_integer: true,
                            message: "Skill assessments may only be numbers" },
            presence: { message: "Please complete all fields" }

  # spambot honeypot
  validates :country,
            # inclusion: { in: [''] },
            presence: false


  # send our application with form_mailer
  after_create :send_my_application

  def send_my_application
    FormMailer.completed_form_email(self).deliver_now!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emailer_forms_controller.rb
class EmailerFormsController < ApplicationController

  # GET /emailer_forms/new
  def new
    @emailer_form = EmailerForm.new
  end

  # POST /emailer_forms
  def create
    @emailer_form = EmailerForm.new(emailer_form_params)

    respond_to do |format|
      if @emailer_form.save
        format.html { redirect_to sent_path, notice: 'Your application was sent successfully!' }
      else
        format.html { render :new }
      end
    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def emailer_form_params
      params.require(:emailer_form).permit( :name,
                                            :email,
                                            :proj_repo,
                                            :proj_url,
                                            :oop,
                                            :modular,
                                            :full_stack,
                                            :testing,
                                            :db,
                                            :debugging,
                                            :problem_solving,
                                            :js,
                                            :html,
                                            :css,
                                            :teamwork,
                                            :self_motivation,
                                            :communication,
                                            :energy_level,
                                            :aptitude,
                                            :country #honeypot
                                          )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emailer_forms_helper.rb
module EmailerFormsHelper
end

app/views/emailer_forms/_form.html.erb
<div class="form-container">
  <div class="form">
    <%= form_for(emailer_form) do |f| %>
      <% if emailer_form.errors.any? %>
        <div id="error_explanation">
          <h1>Oops!</h1>
          <h2>Looks like we have <%= pluralize(emailer_form.errors.count, "problem") %>:</h2>

          <div class="divider"></div>

          <ul>
          <% emailer_form.errors.each do | attrribute, message| %>
            <!-- do nothing with attribute -->
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <% if notice %>
        <h1 id="notice"><%= notice %></h1>
      <% end %>

      <div class="applicant-info">
        <%= f.text_field :name, placeholder: 'full name', required: true %>
        <br>
        <%= f.email_field :email, placeholder: 'email', required: true %>
        <br>
        <%= f.text_field :proj_repo, placeholder: 'project repo', required: true %>
        <br>
        <%= f.text_field :proj_url, placeholder: 'project url', required: true %>
      </div>

      <!-- applicant self-assessment -->
      <div class="assessment-item">
        <%= f.label :oop, "Using best practices for OOP:", class: "assessment-lable" %>
        <%= f.text_field :oop, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :modular, "Modular development:", class: "assessment-lable" %>
        <%= f.text_field :modular, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :full_stack, "Full-stack workflow understanding:", class: "assessment-lable" %>
        <%= f.text_field :full_stack, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :testing, "Testing:", class: "assessment-lable" %>
        <%= f.text_field :testing, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :db, "Database knowledge:", class: "assessment-lable" %>
        <%= f.text_field :db, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :debugging, "Debugging:", class: "assessment-lable" %>
        <%= f.text_field :debugging, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :problem_solving, "Problem solving skills:", class: "assessment-lable" %>
        <%= f.text_field :problem_solving, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :js, "JavaScript:", class: "assessment-lable" %>
        <%= f.text_field :js, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :html, "HTML:", class: "assessment-lable" %>
        <%= f.text_field :html, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :css, "CSS:", class: "assessment-lable" %>
        <%= f.text_field :css, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :teamwork, "Working on a team:", class: "assessment-lable" %>
        <%= f.text_field :teamwork, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :self_motivation, "Self motivation:", class: "assessment-lable" %>
        <%= f.text_field :self_motivation, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :communication, "Communications skills:", class: "assessment-lable" %>
        <%= f.text_field :communication, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :energy_level, "Your own energy level:", class: "assessment-lable" %>
        <%= f.text_field :energy_level, required: true %>
      </div>
      <div class="assessment-item">
        <%= f.label :aptitude, "Intelligence / Aptitude:", class: "assessment-lable" %>
        <%= f.text_field :aptitude, required: true %>
      </div>

      <div class="hidden">
        <%= f.label :country %>
        <%= f.text_field :country %>
      </div>
      <br>

      <%= f.submit 'Submit', class: "actions button" %>
    <% end %>
  </div>
</div>

app/views/emailer_forms/edit.html.erb
<h1>Editing Emailer Form</h1>

<%= render 'form', emailer_form: @emailer_form %>

<%= link_to 'Show', @emailer_form %> |
<%= link_to 'Back', emailer_forms_path %>

app/views/emailer_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emailer Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Proj repo</th>
      <th>Proj url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emailer_forms.each do |emailer_form| %>
      <tr>
        <td><%= emailer_form.name %></td>
        <td><%= emailer_form.email %></td>
        <td><%= emailer_form.proj_repo %></td>
        <td><%= emailer_form.proj_url %></td>
        <td><%= link_to 'Show', emailer_form %></td>
        <td><%= link_to 'Edit', edit_emailer_form_path(emailer_form) %></td>
        <td><%= link_to 'Destroy', emailer_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emailer Form', new_emailer_form_path %>

app/views/emailer_forms/new.html.erb
<%= render 'form', emailer_form: @emailer_form %>

app/views/emailer_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emailer_form.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emailer_form.email %>
</p>

<p>
  <strong>Proj repo:</strong>
  <%= @emailer_form.proj_repo %>
</p>

<p>
  <strong>Proj url:</strong>
  <%= @emailer_form.proj_url %>
</p>

<%= link_to 'Edit', edit_emailer_form_path(@emailer_form) %> |
<%= link_to 'Back', emailer_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TRIM AGENCY | Apprenticeship Application</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>